//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Plus.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("257")]
        public int MainStoreInsertSplitterDistance {
            get {
                return ((int)(this["MainStoreInsertSplitterDistance"]));
            }
            set {
                this["MainStoreInsertSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7878")]
        public int SateliteTcpPort {
            get {
                return ((int)(this["SateliteTcpPort"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string DaysOfStockRotation {
            get {
                return ((string)(this["DaysOfStockRotation"]));
            }
            set {
                this["DaysOfStockRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string DaysOfMinAmount {
            get {
                return ((string)(this["DaysOfMinAmount"]));
            }
            set {
                this["DaysOfMinAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204")]
        public int DefectSplitterDistance {
            get {
                return ((int)(this["DefectSplitterDistance"]));
            }
            set {
                this["DefectSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public string DaysForAnalysis {
            get {
                return ((string)(this["DaysForAnalysis"]));
            }
            set {
                this["DaysForAnalysis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string ProductSuppliesTopRows {
            get {
                return ((string)(this["ProductSuppliesTopRows"]));
            }
            set {
                this["ProductSuppliesTopRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("270")]
        public int frmProductSupplies_SplitterDistance {
            get {
                return ((int)(this["frmProductSupplies_SplitterDistance"]));
            }
            set {
                this["frmProductSupplies_SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string frmMainStoreInsert_ProductSuppliesTopRows {
            get {
                return ((string)(this["frmMainStoreInsert_ProductSuppliesTopRows"]));
            }
            set {
                this["frmMainStoreInsert_ProductSuppliesTopRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public string StandartExtra {
            get {
                return ((string)(this["StandartExtra"]));
            }
            set {
                this["StandartExtra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2010-01-01")]
        public global::System.DateTime SuppliersSummariesStartDate {
            get {
                return ((global::System.DateTime)(this["SuppliersSummariesStartDate"]));
            }
            set {
                this["SuppliersSummariesStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OverridedIPs {
            get {
                return ((string)(this["OverridedIPs"]));
            }
            set {
                this["OverridedIPs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbHost {
            get {
                return ((string)(this["DbHost"]));
            }
            set {
                this["DbHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbUser {
            get {
                return ((string)(this["DbUser"]));
            }
            set {
                this["DbUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbPassword {
            get {
                return ((string)(this["DbPassword"]));
            }
            set {
                this["DbPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source={0};Initial Catalog=sklad;User ID={1};Password={2};Persist Security I" +
            "nfo=True;")]
        public string ConnectionStringTemplate {
            get {
                return ((string)(this["ConnectionStringTemplate"]));
            }
            set {
                this["ConnectionStringTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source={0};User ID={1};Password={2};Initial Catalog=p{3};Persist Security In" +
            "fo=True;")]
        public string ConnectionStringStoreTemplate {
            get {
                return ((string)(this["ConnectionStringStoreTemplate"]));
            }
            set {
                this["ConnectionStringStoreTemplate"] = value;
            }
        }
    }
}
